# Copyright (c) 2025 Andrey Dubovik <andrei at dubovik dot eu>

"""Unicode to LaTeX transliteration tables."""

VARIABLES = {
    # Greek
    'Α': r'\Alpha',
    'Β': r'\Beta',
    'Γ': r'\Gamma',
    'Δ': r'\Delta',
    'Ε': r'\Epsilon',
    'Ζ': r'\Zeta',
    'Η': r'\Eta',
    'Θ': r'\Theta',
    'Ι': r'\Iota',
    'Κ': r'\Kappa',
    'Λ': r'\Lambda',
    'Μ': r'\Mu',
    'Ν': r'\Nu',
    'Ξ': r'\Xi',
    'Ο': r'\Omicron',
    'Π': r'\Pi',
    'Ρ': r'\Rho',
    'Σ': r'\Sigma',
    'Τ': r'\Tau',
    'Υ': r'\Upsilon',
    'Φ': r'\Phi',
    'Χ': r'\Chi',
    'Ψ': r'\Psi',
    'Ω': r'\Omega',

    'α': r'\alpha',
    'β': r'\beta',
    'γ': r'\gamma',
    'δ': r'\delta',
    'ε': r'\epsilon',
    'ζ': r'\zeta',
    'η': r'\eta',
    'θ': r'\theta',
    'ι': r'\iota',
    'κ': r'\kappa',
    'λ': r'\lambda',
    'μ': r'\mu',
    'ν': r'\nu',
    'ξ': r'\xi',
    'ο': r'\omicron',
    'π': r'\pi',
    'ρ': r'\rho',
    'σ': r'\sigma',
    'τ': r'\tau',
    'υ': r'\upsilon',
    'φ': r'\phi',
    'χ': r'\chi',
    'ψ': r'\psi',
    'ω': r'\omega',
}
